spring:
  application:
    name: default-config-server  
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
